[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"

[[example]]
name = "Vector"
path = "Collections/Vector.rs"

[[example]]
name = "Hashmaps"
path = "Collections/Hashmaps.rs"

[[example]]
name = "convert_tohashmap"
path = "Collections/convert_tohashmap.rs"
